### ISSUE TITLE
Doesn't build with zita-convolver-4.0.0

### ISSUE THREAD

**Issue by yurivict** [Anchakor/ir.lv2#10]
The build fails:
```
c++ ir.cc  -Wall -I. -I/usr/include `pkg-config --cflags gtk+-2.0` `pkg-config --cflags gthread-2.0` -D__STDC_FORMAT_MACROS -O2 -ffast-math -D_HAVE_GTK_ATLEAST_2_20 -c -fPIC -o ir.o
ir.cc:40:2: error: "This version of IR requires zita-convolver 3.x.x"
#error "This version of IR requires zita-convolver 3.x.x"
 ^
ir.cc:526:9: error: no member named 'set_density' in 'Convproc'
                conv->set_density(1);
                ~~~~  ^
ir.cc:533:24: error: too few arguments to function call, expected 7, have 6
                                  Convproc::MAXPART);
                                                   ^
/usr/local/include/zita-convolver.h:387:5: note: 'configure' declared here
    int configure (uint32_t  ninp,
    ^
```

**Comment by Anchakor** [comment]
I don't really have the time for maintaining this fork. The original author created a repo https://github.com/tomszilagyi/ir.lv2, I would prefer for the plugin to be just one repo with the best version of it. I will still merge PRs but sadly I don't have time outside of that.

**Comment by yurivict** [comment]
You should submit the delta, if any, to https://github.com/tomszilagyi/ir.lv2 as a pull request, and label this repo as a fork of tomszilagyi/ir.lv. Otherwise, it isn't obvious what the main repository is.
